# Generated by Django 5.1 on 2024-08-26 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyServerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('location', models.CharField(max_length=255)),
                ('admin_contact', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CacheLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('cache_status', models.CharField(help_text='Status cache seperti HIT, MISS, dll.', max_length=50)),
                ('client_address', models.GenericIPAddressField()),
                ('bytes', models.IntegerField(help_text='Jumlah byte yang di-cache')),
                ('request_method', models.CharField(max_length=10)),
                ('request_url', models.URLField()),
                ('mime_type', models.CharField(max_length=255)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestfulApi.proxyserverinfo')),
            ],
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('elapsed_time', models.IntegerField(help_text='Waktu yang dihabiskan untuk permintaan dalam milidetik')),
                ('client_address', models.GenericIPAddressField()),
                ('result_code', models.CharField(max_length=50)),
                ('bytes', models.IntegerField(help_text='Jumlah byte yang dikirim ke klien')),
                ('request_method', models.CharField(max_length=10)),
                ('request_url', models.URLField()),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('hierarchy_code', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestfulApi.proxyserverinfo')),
            ],
        ),
        migrations.CreateModel(
            name='StoreLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('action', models.CharField(help_text='Tindakan seperti RELEASE, SWAPOUT, dll.', max_length=50)),
                ('object_size', models.IntegerField(help_text='Ukuran objek dalam byte')),
                ('request_url', models.URLField()),
                ('client_address', models.GenericIPAddressField()),
                ('http_status', models.CharField(max_length=10)),
                ('mime_type', models.CharField(max_length=255)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestfulApi.proxyserverinfo')),
            ],
        ),
        migrations.CreateModel(
            name='UserAgentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('user_agent', models.CharField(max_length=1024)),
                ('ip_address', models.GenericIPAddressField()),
                ('request_url', models.URLField()),
                ('http_method', models.CharField(max_length=10)),
                ('response_status', models.CharField(max_length=10)),
                ('response_size', models.IntegerField()),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestfulApi.proxyserverinfo')),
            ],
        ),
        migrations.CreateModel(
            name='SquidLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('access_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RestfulApi.accesslog')),
                ('cache_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RestfulApi.cachelog')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestfulApi.proxyserverinfo')),
                ('store_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RestfulApi.storelog')),
                ('user_agent_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RestfulApi.useragentlog')),
            ],
        ),
    ]
