# Generated by Django 4.2.16 on 2024-09-13 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestfulApi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesslog',
            old_name='username',
            new_name='host',
        ),
        migrations.RenameField(
            model_name='accesslog',
            old_name='hierarchy_code',
            new_name='http_status',
        ),
        migrations.RemoveField(
            model_name='accesslog',
            name='result_code',
        ),
        migrations.RemoveField(
            model_name='accesslog',
            name='type',
        ),
    ]
