# Generated by Django 4.2.16 on 2024-09-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestfulApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxyserverinfo',
            name='system_operation',
            field=models.CharField(default='FreeBsd', max_length=255),
        ),
    ]
