# Generated by Django 4.2.16 on 2024-09-25 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RestfulApi', '0002_proxyserverinfo_system_operation'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=255, verbose_name='Nama Lengkap')),
                ('no_ktp', models.CharField(max_length=255, verbose_name='No Ktp')),
                ('jenis_kelamin', models.CharField(choices=[('Laki-Laki', 'Laki-Laki'), ('Perempuan', 'Perempuan')], max_length=255, verbose_name='Jenis Kelamin')),
                ('no_telp', models.CharField(max_length=255, verbose_name='No Telpon')),
                ('tempat_lahir', models.CharField(max_length=255, verbose_name='Tempat Lahir')),
                ('tanggal_lahir', models.DateField(verbose_name='Tanggal Lahir')),
                ('npwp', models.CharField(max_length=255, verbose_name='NPWP')),
                ('agama', models.CharField(max_length=255, verbose_name='Agama')),
                ('alamat_ktp', models.CharField(max_length=255, verbose_name='Alamat KTP')),
                ('alamat_domisili', models.CharField(max_length=255, verbose_name='Alamat Domisili')),
                ('data_owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ID User')),
            ],
        ),
    ]
