# Generated by Django 4.2.16 on 2024-10-10 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestfulApi', '0003_userdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cachelog',
            old_name='mime_type',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='cachelog',
            name='bytes',
        ),
        migrations.RemoveField(
            model_name='cachelog',
            name='cache_status',
        ),
        migrations.RemoveField(
            model_name='cachelog',
            name='client_address',
        ),
        migrations.RemoveField(
            model_name='cachelog',
            name='request_method',
        ),
        migrations.RemoveField(
            model_name='cachelog',
            name='request_url',
        ),
        migrations.RemoveField(
            model_name='cachelog',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='storelog',
            name='size',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='storelog',
            name='timestamp',
            field=models.CharField(max_length=255),
        ),
    ]
